// File generated by Sage, do not edit!

import React from "react";
import type { SageFileComponent } from "../../sage/components";
import Code from "../../sage/components/Code"; // Controlled via sage.config

const CodePage: SageFileComponent = (props) => {
  return <Code {...props} />;
};

export default CodePage;

CodePage.resource = {
  id: "code.foo.ts",
  kind: "code",
  name: "foo",
  crumbs: ["root"],
  meta: {
    language: "typescript",
    short: "FooCode",
  },
  processed:
    '<span class="hljs-keyword">export</span> <span class="hljs-keyword">const</span> <span class="hljs-title function_">gnurp</span> = (<span class="hljs-params">foo: <span class="hljs-built_in">string</span></span>) =&gt; {\n  <span class="hljs-keyword">const</span> bar = <span class="hljs-title function_">baz</span>() <span class="hljs-keyword">as</span> { <span class="hljs-attr">harp</span>: <span class="hljs-built_in">number</span>; <span class="hljs-attr">marp</span>: <span class="hljs-built_in">boolean</span> }\n  <span class="hljs-keyword">return</span> bar\n}\n',
  type: "file",
};
