// File generated by Sage, do not edit!

import React from "react";
import type { SageFolderComponent } from "../../sage/components";
import Folder from "../../sage/components/Folder"; // Controlled via sage.config

const FolderPage: SageFolderComponent = (props) => {
  return <Folder {...props} />;
};

export default FolderPage;

FolderPage.resource = {
  id: "hurp",
  crumbs: ["root"],
  meta: {
    title: "Hurp!",
  },
  contains: ["graph.fnerp.dot", "markdown.meep.md"],
  type: "folder",
};
