// File generated by Sage, do not edit!

import React from "react";
import type { SageRootComponent } from "../sage/components";
import Root from "../sage/components/Root"; // Controlled via sage.config

const RootPage: SageRootComponent = (props) => {
  return <Root {...props} />;
};

export default RootPage;

RootPage.resource = {
  id: "root",
  crumbs: [],
  meta: {
    title: "My awesome lecture",
  },
  contains: ["hurp", "code.foo.ts"],
  type: "root",
};
