// File generated by Sage, do not edit!

import React from "react";
import type { SageFileComponent } from "../../sage/components";
import Markdown from "../../sage/components/Markdown"; // Controlled via sage.config

const MarkdownPage: SageFileComponent = (props) => {
  return <Markdown {...props} />;
};

export default MarkdownPage;

MarkdownPage.resource = {
  id: "markdown.meep.md",
  kind: "markdown",
  name: "meep",
  crumbs: ["root", "hurp"],
  meta: {},
  processed:
    '<h3 id="woo">Woo!</h3>\n<ul>\n<li>foo</li>\n<li>bar</li>\n<li>baz!</li>\n</ul>\n',
  type: "file",
};
